--- 
error: 
  whitelabel: 
    enabled: false
eureka: 
  client: 
    register-with-eureka: false
    service-url: 
      defaultZone: "http://localhost:9000/eureka/"
server: 
  port: 9091
spring: 
  application: 
    name: google-note-micro  datasource:    url: jdbc:mysql://localhost:3306/googlenote
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:    hibernate:      ddl-auto: create


   

